"""SQLAlchemy declarative base and shared mixins for Lucifex models.

All models in `lucifex.db.models` inherit from `Base`. Models opt in to the
mixins they need to gain shared fields: `IdMixin`, `TimestampMixin`,
`SoftDeleteMixin`.

The split between Base and Mixins is deliberate. Base provides only what
SQLAlchemy requires for declarative mapping. Mixins add fields that some
tables need and others don't. Append-only tables (analytics_snapshots,
audit_log, status_history, agent_messages, job_runs) take TimestampMixin
but NOT SoftDeleteMixin — they are never soft-deleted.

See `docs/architecture.md` for the full data model.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

from sqlalchemy import DateTime, MetaData
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# ---------------------------------------------------------------------------
# Naming conventions
# ---------------------------------------------------------------------------
# Postgres requires unique names for indexes and constraints. Without a
# convention, autogenerated names from Alembic can collide or change between
# runs, producing noisy migrations. The naming convention below is the
# Alembic-recommended default and gives every constraint a deterministic name.
# ---------------------------------------------------------------------------

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """The declarative base for all Lucifex models.

    Carries only what SQLAlchemy requires. Field mixins are separate so
    each model picks what it needs.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# ---------------------------------------------------------------------------
# Helper for timestamp default
# ---------------------------------------------------------------------------


def _utcnow() -> datetime:
    """Return current UTC time as a timezone-aware datetime.

    SQLAlchemy's func.now() is fine for server-side defaults, but having a
    Python-side callable lets us also use the same default in tests, fixtures,
    and any code that constructs models without inserting them.
    """
    return datetime.now(UTC)


# ---------------------------------------------------------------------------
# Mixins
# ---------------------------------------------------------------------------


class IdMixin:
    """UUID primary key. Application-generated.

    Generating UUIDs application-side (rather than relying on a database
    default) makes IDs available before insert — useful for logging, audit
    trails, and constructing related rows in the same transaction.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )


class TimestampMixin:
    """`created_at` and `updated_at` timestamps.

    Both are timezone-aware UTC. `created_at` is set on insert and never
    changes. `updated_at` is set on insert and updated on every change.

    Both have server-side defaults so the database fills them in even if
    the application forgets — defensive against bugs in application code.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=_utcnow,
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=_utcnow,
        onupdate=_utcnow,
        nullable=False,
    )


class SoftDeleteMixin:
    """`deleted_at` for soft delete.

    NULL means the row is live. A timestamp means the row was deleted at
    that time. Application code is responsible for filtering deleted rows
    out of normal queries; this mixin only provides the field.

    Append-only tables (analytics, audit log, status history, agent
    messages, job runs) do NOT use this mixin — they are never deleted.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
    )


# ---------------------------------------------------------------------------
# Type alias for any model class
# ---------------------------------------------------------------------------


ModelType = type[Base]
